### ISSUE TITLE
unicode control characters trigger `debug_assert_eq`

### ISSUE THREAD

**Issue by CommanderStorm** [Aetf/unicode-truncate#16]
Hello,

Thanks for writing the truncation code ^^

During testing of this library, I noticed that carefully crafted inputs containing control caracters can trigger an assertion. This only happens in in debug mode => not a runtime panic for release. The used character is [`End of Medium`](https://www.compart.com/en/unicode/U+0019).

The assertion is located here
https://github.com/Aetf/unicode-truncate/blob/9e49ef4f9ac4e140b854a655daf4bc1d096adf5d/src/lib.rs#L174

A minimal (failing) testcase is the following

```rust
#[cfg(test)]
mod tests {
  #[test]
  fn zero_width_control_char() {
      std::assert_eq!("\u{0019}".unicode_truncate(2), ("\u{0019}", 0));
  }
}
```

This happens because at said point (expanded for better readability)

- ```
  let (byte_index, new_width) = (1, 0);
  ```
- ```
  let result = "\u{0019}".get(..1).unwrap();
  ```
- ```
  let result = "\u{0019}";
  ```
- => thus the `result.width()` (=1) is larger than the `new_width` (=0).

This case happens as `(self.len(), 0)` is appended to the interator.
This makes the iterator (as intended by the doccomment) eager for trailing zero width characters.
=> The asserted invariant does not hold anymore.

A possible fix would be to change the assertion to
```diff
- debug_assert_eq!(result.width(), new_width);
+ debug_assert!(result.width() >= new_width);
```

I can provide a PR with this fix if you'd prefer this

**Comment by CommanderStorm** [comment]
(this was likely introduced in `unicode-width=0.1.13` via https://github.com/unicode-rs/unicode-width/pull/45)

**Comment by Aetf** [comment]
This is a legit logic error caught by `debug_assert_eq`.

The problem is that we control char to be of width 0 here: https://github.com/Aetf/unicode-truncate/blob/9e49ef4f9ac4e140b854a655daf4bc1d096adf5d/src/lib.rs#L155

But unicode-width treats control char as width 1 via unicode-rs/unicode-width#45

**Comment by CommanderStorm** [comment]
Thanks a ton ♥️
